# Generated by Django 5.2.6 on 2025-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('faculte', models.CharField(choices=[('Sciences Administratives', 'Sciences Administratives'), ("Sciences de l'Éducation", "Sciences de l'Éducation")], max_length=100, verbose_name='Faculté choisie')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('traite', models.BooleanField(default=False, verbose_name='Dossier Traité')),
            ],
            options={
                'verbose_name': "Demande d'Admission",
                'verbose_name_plural': "Demandes d'Admission",
                'ordering': ['-date_demande'],
            },
        ),
    ]
